### ISSUE TITLE
Update to 0.3.3 fails

### ISSUE THREAD

**Issue by rdwz** [deta/space-cli#100]
PowerShell 7.3.4

$ space version upgrade
> Upgrading Space CLI to version 0.3.3...
> iex : Ausnahme beim Aufrufen von "ExtractToDirectory" mit 2 Argument(en):  "Die Datei
> "C:\Users\Rychart\.detaspace\bin\LICENSE" ist bereits vorhanden."
> In Zeile:1 Zeichen:65
> + $v="0.3.3"; iwr https://deta.space/assets/space-cli.ps1 -useb | iex
> +                                                                 ~~~
>     + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
>     + FullyQualifiedErrorId : IOException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
>
>
> ❌  Upgrade failed. Please try again.

$ space
> space: The term 'space' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by pomdtr** [comment]
It looks like this is related to the windows antivirus stopping the space binary to run. We should just print the installation message again instead.
