### ISSUE TITLE
[Bug] wrong version update tips

### ISSUE THREAD

**Issue by lizheming** [deta/space-cli#106]
I'm the latest version, but still has a new version available tips. While I run `space version upgrade` command, it shows `no upgrade required` 

![image](https://github.com/deta/space-cli/assets/424491/363ad34d-2dff-4b26-97ef-508765f3063e)

**Comment by abdelhai** [comment]
@brkp would be cool to look into this

**Comment by brkp** [comment]
Went through the code, nothing sticks out that might cause this. You most likely had a corrupted `~/.detaspace` folder. Please re-open the issue if it still persists.
