### ISSUE TITLE
Unable to locate package wget

### ISSUE THREAD

**Issue by appsdevpk** [deta/space-cli#120]
i build a custom php app 2 months ago, it is still working, today i tried to create another one with same space file configuration but failed with below output
![image](https://github.com/deta/space-cli/assets/516860/553369c9-fca9-42b0-b71a-0a56497c94d8)
 my space file is as below

![image](https://github.com/deta/space-cli/assets/516860/3af32b17-5d02-45f7-bb97-7f3a5639e328)

**Comment by abdelhai** [comment]
@pomdtr @aavshr could we add wget to the builder?

**Comment by pomdtr** [comment]
@appsdevpk can you add `apt-get update` as you first command ?

I'll add wget to the default image.

**Comment by appsdevpk** [comment]
now this
![image](https://github.com/deta/space-cli/assets/516860/28dfe489-d6e7-4bd3-b227-8bc78868f063)

**Comment by pomdtr** [comment]
Probably related to weird newlines or incoherent tab / space usage. Your files is not a valid yaml file
