### ISSUE TITLE
[Micro Error] Next App build failed on micro

### ISSUE THREAD

**Issue by epicstellargamesstudio** [deta/space-cli#122]
I keep getting 
```Running Command: cp -r .next/static .next/standalone/.next/static```

 and then at the second line
 ```
cp: cannot create directory 'next/standalone/.next/static': No such file or directory 
``` 

I don't know why i am getting this error.

**Comment by abdelhai** [comment]
follow the steps: https://deta.space/docs/en/build/quick-starts/next#content
