### ISSUE TITLE
after this new commit the space commit wont working ....

### ISSUE THREAD

**Issue by xalteropsx** [deta/space-cli#126]
![image](https://github.com/deta/space-cli/assets/103671642/31e9d6ea-8d65-4516-9d2f-2a6ed3ae1ce7)
![image](https://github.com/deta/space-cli/assets/103671642/3271ca00-ea06-4acf-8784-6f8dccf5f04a)

**Comment by abdelhai** [comment]
please use discord [discord.gg/deta](https://discord.gg/deta)
