### ISSUE TITLE
space login "failed to validate token"

### ISSUE THREAD

**Issue by akpi816218** [deta/space-cli#132]
Maybe important: I'm using Termux because I'm in India for a couple of days

When running `space login`, an error is thrown after providing the token:
```bash
$ space login
To authenticate the Space CLI with your Space account, generate a new access token in your Space settings and paste it below:

? Enter access token (41 chars) > **********************
! Failed to validate access token: failed to compute timestamp shift: failed to fetch timestamp: Get "https://deta.space/api/v0/time": dial tcp: lookup deta.space on [::1]:53: read udp [::1]:37766->[::1]:53: read: connection refused
! Failed to login: failed to validate access token: failed to compute timestamp shift: failed to fetch timestamp: Get "https://deta.space/api/v0/time": dial tcp: lookup deta.space on [::1]:53: read udp [::1]:37766->[::1]:53: read: connection refused
Error: failed to validate access token: failed to compute timestamp shift: failed to fetch timestamp: Get "https://deta.space/api/v0/time": dial tcp: lookup deta.space on [::1]:53: read udp [::1]:37766->[::1]:53: read: connection refused
$
```

I asked about this on the Discord server, and someone on the team asked me if I could access https://deta.space/api/v0/time via my browser. I can access it via the browser. `curl https://deta.space/api/v0/time` prints the current UNIX timestamp, which is what I see in the browser.

I will try again on my laptop and desktop when I get back home and edit this issue with the results.

**Comment by abdelhai** [comment]
make sure your computer clock is set correctly if you're still facing this issue.

**Comment by n-ce** [comment]
I face the same issue on termux
