### ISSUE TITLE
Compilation target windows 7 x32

### ISSUE THREAD

**Issue by baterflyrity** [deta/space-cli#133]
Hi!

Can anybody help me with compiling deta space cli targeting windows 7 (32 bit)?

I've tried to cross-compile on ubuntu 22.04 using both standard and mingw toolchains. Unfortunately, binaries fail in `space new` with "*can not switch console to raw mode*" error. Also `space version` works fine.

p.s.
Am i missing non-interactive space cli mode?

**Comment by abdelhai** [comment]
why do you need 32 bit? that's pretty outdated.
the cli has a non-interactive mode. just provide the required args. let me know where you have issues..

**Comment by baterflyrity** [comment]
Thanks. Seems like I've missed these options.

> why do you need 32 bit? that's pretty outdated

Sure, I use 32-bit laptop. Hence need to cross-compile under linux server and stuck at pty problem in windows console.
