### ISSUE TITLE
[Feature Request] Support for Python 3.10

### ISSUE THREAD

**Issue by diamond-fish** [deta/space-cli#145]
My Python API hosted on Deta Space wasn't working when I followed the [FastAPI tutorial](https://fastapi.tiangolo.com/tutorial/), and I found out it was because Space doesn't support Python 3.10 at the moment.

Are there plans to add support for Python 3.10? If yes, what's the best way for me to be informed when the support is added?

**Comment by abdelhai** [comment]
coing soon
