### ISSUE TITLE
Don't commit (.space) folder to git

### ISSUE THREAD

**Issue by adlaternae** [deta/space-cli#59]
to not commit any folder to git, just add `.gitignore` file contains `*` to folder

Ex. line105 `ioutil.WriteFile(filepath.Join(m.spacePath, ".gitignore"), []byte("*\n"), filePermMode)`
https://github.com/deta/space-cli/blob/aa93f1476e56268fab0c4444db1e6326feb8f59f/internal/runtime/manager.go#L105
thnx

**Comment by abdelhai** [comment]
hi sorr, i'm not sure i understand this issue. could you please rephrase?
